---
################################################################################
#
# Install Webmin
#
################################################################################
- name: Install webmin
  hosts: all
  become: true
  user: ansible
  connection: ssh 

  ###
  tasks:

  ###
  - debug: var=ansible_distribution

################################################################################
# Debian/Ubuntu/Raspbian section
################################################################################

  ###
  - name: Check if webmin is installed (Debian)
    command: dpkg-query -W webmin
    register: webmin_check_deb
    failed_when: webmin_check_deb.rc > 1
    changed_when: webmin_check_deb.rc == 1
    when: ansible_distribution == 'Debian' or
          ansible_distribution == 'Ubuntu' or
          ansible_distribution == 'Raspbian'

  ###
  - name: Install webmin required packages (Debian)
    apt:
      name: "{{ apt_packages }}"
    vars:
      apt_packages:
      - perl
      - libnet-ssleay-perl
      - openssl
      - libauthen-pam-perl
      - libpam-runtime
      - libio-pty-perl
      - apt-show-versions
      - python
    when: webmin_check_deb.rc == 1

  ###
  - name: Download webmin package (Debian)
    get_url: 
      url="{{ deb_pkg }}"
      dest="/tmp/webmin.deb"
    when: webmin_check_deb.rc == 1

  ###
  - name: Install webmin (Debian)
    apt: deb="/tmp/webmin.deb"
    when: webmin_check_deb.rc == 1


################################################################################
# CentOS/RedHat section
################################################################################

  ###
  - name: Check if webmin is installed (CentOS)
    command: rpm -q webmin
    register: webmin_check_rpm
    failed_when: webmin_check_rpm.rc > 1
    changed_when: webmin_check_rpm.rc == 1
    when: ansible_distribution == 'CentOS' or
          ansible_distribution == 'Red Hat Enterprise Linux' 

  ###
  - name: Install webmin required packages (CentOS)
    name:
      name: "{{ rpm_packages }}"
    vars:
      rpm_packages:
      - perl
      - perl-Net-SSLeay
      - openssl
      - perl-IO-Tty
      - perl-Encode-Detect
    when: webmin_check_rpm.rc == 1

  ###
  - name: Download webmin package (CentOS)
    get_url: 
      url="{{ rpm_pkg }}"
      dest="/tmp/webmin.rpm"
    when: webmin_check_rpm.rc == 1

  ###
  - name: Install webmin (CentOS)
    apt: deb="/tmp/webmin.rpm"
    when: webmin_check_rpm.rc == 1
